// Code generated by MockGen. DO NOT EDIT.
// Source: ./watcher/kwpoll/pollwatcher.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	time "time"
)

// MockRater is a mock of Rater interface
type MockRater struct {
	ctrl     *gomock.Controller
	recorder *MockRaterMockRecorder
}

// MockRaterMockRecorder is the mock recorder for MockRater
type MockRaterMockRecorder struct {
	mock *MockRater
}

// NewMockRater creates a new mock instance
func NewMockRater(ctrl *gomock.Controller) *MockRater {
	mock := &MockRater{ctrl: ctrl}
	mock.recorder = &MockRaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRater) EXPECT() *MockRaterMockRecorder {
	return m.recorder
}

// Time mocks base method
func (m *MockRater) Time() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Time")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// Time indicates an expected call of Time
func (mr *MockRaterMockRecorder) Time() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Time", reflect.TypeOf((*MockRater)(nil).Time))
}

// MockGetter is a mock of Getter interface
type MockGetter struct {
	ctrl     *gomock.Controller
	recorder *MockGetterMockRecorder
}

// MockGetterMockRecorder is the mock recorder for MockGetter
type MockGetterMockRecorder struct {
	mock *MockGetter
}

// NewMockGetter creates a new mock instance
func NewMockGetter(ctrl *gomock.Controller) *MockGetter {
	mock := &MockGetter{ctrl: ctrl}
	mock.recorder = &MockGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockGetter) EXPECT() *MockGetterMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockGetter) Get() (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockGetterMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGetter)(nil).Get))
}
